smileys:
  smiley1:
    input: ':)'
    output: '☺'
  smiley2:
    input: '(:'
    output: '☺'
  heart:
    input: '<3'
    output: '♥'
  check:
    input: '*check'
    output: '✔'
  shrug:
    input: '*shrug'
    output: '¯\_(ツ)_/¯'
  reddit:
    input: '*reddit'
    output: 'ಠ_ಠ'
  cute:
    input: '*cute'
    output: '(｡◕‿◕｡)'
emotes:
  self:
    #name:
      #message: 'test'
      #description: 'description'
      #material: APPLE
      #data: 0
    cry:
      message: '{player} starts crying'
      description: 'Cry uncontrollably'
    smile:
      message: '{player} starts smiling'
      description: 'Smile with glee'
    laugh:
      message: '{player} starts laughing'
      description: 'Start laughing excitedly'
  other:
    hug:
      message: '{player1} hugs {player2}'
      description: 'Hug the target player'