name: Smileymote
main: io.github.zaxarner.mc.smileymote.Smileymote
version: @plugin.version@
description: Emotes & Smileys
author: Zaxarner
api-version: "1.15"
permissions:
  smileymote.emote:
    description: "Allows using emotes"
  smileymote.smiley:
    description: "Allows using smileys in chat, signs, books, etc"
  smileymote.admin:
    description: "Allows access to Admin commands such as reloading"
    default: op
    children:
      smileymote.emote: true
      smileymote.smiley: true