name: Smileymote
main: com.gmail.zaxarner.smileymote.Smileymote
version: @VERSION@
description: Emotes & Smileys
author: Zaxarner
commands:
    emote:
      description: "Use an emote"
      permission: smileymote.emote
      usage: "/<command> <emote> <player [optional]>"
      aliases: [smote, em]
    smileys:
      description: "Lists all of the smileys"
      permission: smileymote.smiley
      usage: "/<command>"
      aliases: [smiley, smiles]